// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_OG5_Wt_bNqMguaDvW9jhdATD7ECVeQ',
    appId: '1:4216888983:web:9c8e5829f5bc8c14b493d2',
    messagingSenderId: '4216888983',
    projectId: 'pawfect-bf871',
    authDomain: 'pawfect-bf871.firebaseapp.com',
    databaseURL: 'https://pawfect-bf871-default-rtdb.firebaseio.com',
    storageBucket: 'pawfect-bf871.firebasestorage.app',
    measurementId: 'G-YN753L8Y42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWmNFqhxBfTV6KMwhJ7dIKe-pceathjA',
    appId: '1:4216888983:android:a277d4889b42a382b493d2',
    messagingSenderId: '4216888983',
    projectId: 'pawfect-bf871',
    databaseURL: 'https://pawfect-bf871-default-rtdb.firebaseio.com',
    storageBucket: 'pawfect-bf871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1Z8gLQDRRfNO6LzUYebVIi7RID_wfkY',
    appId: '1:4216888983:ios:20ba9f140eb9bdb3b493d2',
    messagingSenderId: '4216888983',
    projectId: 'pawfect-bf871',
    databaseURL: 'https://pawfect-bf871-default-rtdb.firebaseio.com',
    storageBucket: 'pawfect-bf871.firebasestorage.app',
    iosClientId: '4216888983-4uqa31fjct3r57d63n192ufhsiqt4v5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1Z8gLQDRRfNO6LzUYebVIi7RID_wfkY',
    appId: '1:4216888983:ios:20ba9f140eb9bdb3b493d2',
    messagingSenderId: '4216888983',
    projectId: 'pawfect-bf871',
    databaseURL: 'https://pawfect-bf871-default-rtdb.firebaseio.com',
    storageBucket: 'pawfect-bf871.firebasestorage.app',
    iosClientId: '4216888983-4uqa31fjct3r57d63n192ufhsiqt4v5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawfect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw_OG5_Wt_bNqMguaDvW9jhdATD7ECVeQ',
    appId: '1:4216888983:web:acbd253e2a8e46e9b493d2',
    messagingSenderId: '4216888983',
    projectId: 'pawfect-bf871',
    authDomain: 'pawfect-bf871.firebaseapp.com',
    databaseURL: 'https://pawfect-bf871-default-rtdb.firebaseio.com',
    storageBucket: 'pawfect-bf871.firebasestorage.app',
    measurementId: 'G-YB4WVKN8DE',
  );
}
